# Lightning Trainer knobs
max_epochs: ${optim.max_epochs}
check_val_every_n_epoch: 1
log_every_n_steps: 50
devices: 1
accelerator: auto

# Fast path tweaks
num_sanity_val_steps: 0
accumulate_grad_batches: 1
gradient_clip_val: 1.0

# Callbacks
lr_monitor: true
early_stopping:
  enable: false
  monitor: val_acc
  mode: max
  patience: 20
  min_delta: 0.0005

# Compile options (PyTorch 2.x Inductor/Triton)
compile:
  enable: true
  mode: max-autotune
  fullgraph: false
  dynamic: true