_target_: src.models.vit.VisionTransformer
image_size: ${data.img_size}
patch_size: 4         # 32/4 => 8×8=64 tokens (+cls) works well for CIFAR-10
embed_dim: 384
depth: 8
num_heads: 6
mlp_ratio: 4.0
num_classes: 10
dropout: 0.0
attn_dropout: 0.0
grad_ckpt: false
