# @package _global_
# configs/exp/quick_debug.yaml
defaults:
  - /data: cifar_10
  - /model: vit_small
  - /optim: adamw
  - /trainer: lightning
  - _self_

# Fast iteration settings
optim:
  max_epochs: 5
  
trainer:
  check_val_every_n_epoch: 1
  
io:
  batch_size: 128