# Top-level defaults (choose a run recipe below)
defaults:
  - data: cifar_10
  - model: vit_small
  - optim: adamw
  - trainer: lightning
  - _self_

exp_name: "cifar10_vit_sl"

# Global training knobs
seed: 42
device: "cuda"
precision: "bf16-mixed"  # fallback to "16-mixed" if bf16 unsupported
channels_last: true
cudnn_benchmark: true

# Dataloader throughput knobs
io:
  batch_size: 512        # ~16GB GPU-friendly for this ViT; adjust if OOM
  num_workers: 8         # set ~ to your CPU cores
  prefetch_factor: 4
  persistent_workers: true
  pin_memory: true

# Hydra working directories: one-run = one folder under ./output or $OUTPUT_DIR
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR, output}/run_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${oc.env:OUTPUT_DIR, output}/multirun
    subdir: run_${now:%Y-%m-%d_%H-%M-%S}
